###################################################################
# CUSEC 2017
###################################################################

# Basic site setup
title: CUSEC 2017
description: > # this means to ignore newlines until "baseurl:"
  Canadian University Software Engineering Conference (CUSEC) is an awesome conference
  organized by undergraduate students from Canadian universities held in Montreal every
  year.
baseurl: "" # starting with /
url: "http://2017.cusec.net" # the base hostname & protocol for your site
google_analytics: UA-68503004-2 #google analytics code XX-nnnnnnnn-n

# Social network info
social:
    - title: envelope
      url: mailto:info@cusec.net
    - title: twitter
      url: https://twitter.com/cusec
    - title: facebook
      url: https://www.facebook.com/CUSEC-9884406702/
    - title: youtube
      url: https://www.youtube.com/channel/UCZ7j8F6h1CxD-uC0od9rHBw


# Build settings
host: 0.0.0.0
timezone: America/Montreal
encoding: utf-8
incremental: TRUE
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

gems:
    - jekyll-sitemap

include:
    - .htaccess
exclude:
    - "*.less"
    - "*.sublime-project"
    - "*.sublime-workspace"
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - CHANGELOG
    - Capfile
    - Gemfile
    - Gruntfile.js
    - LICENSE
    - README
    - Rakefile
    - config
    - gulpfile.js
    - lib
    - log
    - node_modules
    - package.json
    - spec
    - tmp
